DP-090
MicrosoftLearning/dp-090-databricks-ml pull request #54
Opened 2021-08-30 22:31 UTC by greg-ray-lods

# Module: 00
## Lab/Demo: 00

Fixes # .

Changes proposed in this pull request:

-
-
-

2021-08-30 22:45 UTC, GraemeMalcolm requested changes
Please make the requested changes and resubmit the PR.

Thanks!

2021-08-30 22:45 UTC, GraemeMalcolm commented on Instructions/Labs/01a-introduction-to-azure-databricks.md
> +1. When your Azure Databricks workspace resource has been created, select **Go to Resource** and select **Launch Workspace** to open your Databricks workspace in a new tab, signing in if prompted.
No. Please leave step 1 as-is.

2021-08-30 22:45 UTC, GraemeMalcolm commented on Instructions/Labs/01a-introduction-to-azure-databricks.md
> +1. In the left-hand menu of your Databricks workspace, select **Create**, and then select **Cluster** to add a new cluster with the following configuration:
No. Please change step 2 to:

1. In the left-hand menu of your Databricks workspace, select **Compute**, and then select **+ Create Cluster** to add a new cluster with the following configuration:
   - **Name**: *Enter a unique name.*
   - **Cluster Mode**: Single Node
   - **Pool**: None

2021-08-30 22:45 UTC, GraemeMalcolm commented on Instructions/Labs/01a-introduction-to-azure-databricks.md
> +1. Save `https://raw.githubusercontent.com/MicrosoftLearning/dp-090-databricks-ml/master/data/nyc-taxi.csv` to your computer by copying and pasting the entire page to notepad as **nyc-taxi.csv** in a
No. Please leave as-is

2021-08-30 22:45 UTC, GraemeMalcolm commented on Instructions/Labs/01a-introduction-to-azure-databricks.md
> +If you're finished working with Azure Databricks for now, in the left-hand menu of your Databricks workspace, select **Compute**, then select **■ Terminate** to shut it down. Otherwise, leave it runn
No. Please leave as-is except change "the **Clusters** page" to "the **Compute** page.

2021-08-31 17:07 UTC, merged

2021-08-31 17:26 UTC, greg-ray-lods commented
I made the changes to the dp-090 fork. Are you seeing my pull request?

From: Graeme Malcolm ***@***.***>
Sent: Tuesday, August 31, 2021 12:07 PM
To: MicrosoftLearning/dp-090-databricks-ml ***@***.***>
Cc: Greg Ray ***@***.***>; Author ***@***.***>
Subject: Re: [MicrosoftLearning/dp-090-databricks-ml] DP-090 (#54)

CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe. Also, please think before you reply-all to external recipients.

Merged #54<https://github.com/MicrosoftLearning/dp-090-databricks-ml/pull/54> into master.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/MicrosoftLearning/dp-090-databricks-ml/pull/54#event-5233970794>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AVH2LQ3AWDMB2ZM4SLUFY7DT7UD4JANCNFSM5DCZ5Z3A>.
Triage notifications on the go with GitHub Mobile for iOS<https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675> or Android<https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.

2021-08-31 17:27 UTC, GraemeMalcolm commented
I merged this PR

2021-08-31 17:28 UTC, greg-ray-lods commented
Ok so its complete?


From: Graeme Malcolm ***@***.***>
Sent: Tuesday, August 31, 2021 12:28 PM
To: MicrosoftLearning/dp-090-databricks-ml ***@***.***>
Cc: Greg Ray ***@***.***>; Author ***@***.***>
Subject: Re: [MicrosoftLearning/dp-090-databricks-ml] DP-090 (#54)

CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe. Also, please think before you reply-all to external recipients.

I merged this PR

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/MicrosoftLearning/dp-090-databricks-ml/pull/54#issuecomment-909439016>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AVH2LQZOGQEARNEXH72VGH3T7UGKFANCNFSM5DCZ5Z3A>.
Triage notifications on the go with GitHub Mobile for iOS<https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675> or Android<https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.

2021-08-31 17:29 UTC, GraemeMalcolm commented
Yes - I'll take it from here - thanks